repos:
    -  repo: https://github.com/pycqa/isort
       rev: 5.8.0
       hooks:
       - id: isort

    -   repo: https://github.com/psf/black
        rev: 21.5b2
        hooks:
        - id: black
          language_version: python3.7

        # Refer https://github.com/pre-commit/pre-commit/issues/1206#issuecomment-551000892
    -   repo: https://gitlab.com/pycqa/flake8.git
        rev: 3.7.9
        hooks:
        - id: flake8